import './globals.css'
import Sidebar from "@/components/Sidebar/Sidebar";
import Header from "@/components/Header/Header";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className="bg-black text-gray-300 h-screen max-w-[2560px] w-full p-6 gap-6 font-mono ">
        {children}
        </body>
        </html>
    )
}
